"""Creating students table

Revision ID: a70323b377b0
Revises: d499975c134d
Create Date: 2025-05-25 18:42:54.374642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a70323b377b0'
down_revision = 'd499975c134d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=55), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('enrolled_date', sa.DateTime(), nullable=True),
    sa.CheckConstraint('grade BETWEEN 1 AND 12', name='grade_between_1_and_12'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='unique_email')
    )
    op.create_index(op.f('ix_scholars_name'), 'scholars', ['name'], unique=False)
    op.rename_table('scholars', 'students')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scholars_name'), table_name='scholars')
    op.drop_table('scholars')

    op.rename_table('scholars', 'students')
    # ### end Alembic commands ###
# migration/versions/a70323b377b0_creating_students_table.py